"""ECO volume C family data — wayfinder/tickets/0008-rescore-volume-c.md.
Owned exclusively by this file: no other volume file edits these keys,
so parallel work across volumes never conflicts here.
"""

FAMILY_TAGS = {
    "Bishop's Opening": ("White", 0, -1, 0, 0, 1, 2, 1),
    "Bongcloud Attack": ("White", 0, 2, -1, -2, -2, 1, 1),
    "Center Game": ("White", 1, 1, 1, 0, 0, 2, 1),
    "Center Game Accepted": ("White", 1, 1, 1, 0, 0, 2, 1),
    "Danish Gambit": ("White", 2, 2, 2, 1, -1, 2, 2),
    "Danish Gambit Accepted": ("White", 2, 2, 2, 1, -1, 2, 2),
    "Danish Gambit Declined": ("White", 0, 0, 0, 0, -1, 2, 2),
    "Dresden Opening": ("White", 2, 2, 1, 1, -2, 2, 1),
    "Elephant Gambit": ("Black", 1, 2, 1, 1, -2, 1, 1),
    "Four Knights Game": ("White", -1, -1, -1, -1, 1, 2, 2),
    "French Defense": ("Black", -1, -1, -1, 0, 2, 2, 2),
    "Gunderam Defense": ("Black", 0, 1, 1, -1, -1, 1, 1),
    "Irish Gambit": ("White", 2, 2, 1, 1, -2, 1, 1),
    "Italian Game": ("White", 1, 0, 0, -1, 1, 1, 1),
    "King's Gambit": ("White", 2, 2, 2, 1, -1, 2, 2),
    "King's Gambit Accepted": ("White", 2, 2, 2, 1, -1, 2, 2),
    "King's Gambit Declined": ("White", 1, 0, 0, 0, -1, 2, 2),
    "King's Knight Opening": ("White", 0, 0, 0, 0, 2, 1, 1),
    "King's Pawn Opening": ("White", 0, 1, 0, -1, -1, 1, 1),
    "Latvian Gambit": ("Black", 2, 2, 2, 2, -2, 2, 2),
    "Latvian Gambit Accepted": ("Black", 2, 2, 2, 2, -2, 2, 2),
    "Petrov's Defense": ("Black", -1, -2, -2, -1, 2, 3, 3),
    "Philidor Defense": ("Black", -1, -1, -1, -1, -1, 1, 2),
    "Ponziani Opening": ("White", 0, 0, 0, -1, -1, 2, 2),
    "Portuguese Opening": ("White", 0, 1, 1, -1, -1, 1, 1),
    "Ruy Lopez": ("White", -1, -1, 0, 0, 2, 4, 3),
    "Scotch Game": ("White", 1, 0, 1, 0, 1, 2, 2),
    "Three Knights Opening": ("White", -1, -1, -1, -1, -1, 2, 1),
    "Vienna Gambit, with Max Lange Defense": ("White", 2, 2, 1, 1, -1, 3, 2),
    "Vienna Game": ("White", 0, 0, 0, 0, 0, 2, 2),
}

FAMILY_OVERVIEW = {
    "Bishop's Opening": "A direct approach where White develops the kingside bishop early to b5, often transposing to the Italian Game or Vienna Game. It prepares rapid development and castling while maintaining flexibility in the position.",
    "Bongcloud Attack": "An unconventional and controversial opening where White plays 2.Ke2, violating standard opening principles by moving the king early and blocking the bishop's diagonal. Named after a Chess.com user, it is primarily played as a novelty or joke opening.",
    "Center Game": "A direct strategy where White occupies the center with pawns and develops actively, aiming for quick piece coordination and aggressive play. Black is offered a choice between accepting the center or counterattacking.",
    "Center Game Accepted": "The main line of the Center Game where Black captures on d4, accepting White's center but allowing White rapid development and attacking chances with compensation for the temporarily lost pawn.",
    "Danish Gambit": "An ambitious gambit where White sacrifices one or two pawns (usually the c-pawn) to rapidly develop pieces and seize control of the center. Though solid in nature, Black can defend well with accurate play.",
    "Danish Gambit Accepted": "The main line where Black accepts White's pawn sacrifice, leading to open positions with White having rapid development and attacking chances as compensation for the material.",
    "Danish Gambit Declined": "Black declines the gambit by playing ...d6 or similar moves, avoiding the complications and accepting a passive but solid setup, relying on defensive resources.",
    "Dresden Opening": "A side continuation of the Open Game featuring 1.e4 e5 2.Nf3 Nc6 3.c4, where White transfers the center struggle to the queenside with early c-pawn advances. Less common than main lines but strategically sound.",
    "Elephant Gambit": "A direct and rare gambited response by Black to 1.e4 e5, playing 2...d5 immediately to challenge White's center. It violates classical principles but can lead to sharp, unbalanced positions.",
    "Four Knights Game": "A classical and solid opening where both players develop knights to standard squares early, leading to quiet positions with balanced play. Often used to avoid theoretical complications in other 1.e4 e5 openings.",
    "French Defense": "A solid and popular defense against 1.e4 where Black plays 1...e6 and 2...d5, creating a strong pawn chain in the center. Black accepts a slight space disadvantage but gains a very stable position with good counterplay.",
    "Gunderam Defense": "An unusual system by Black featuring an early queen move to e7 (or fianchetto setup), avoiding typical Open Game structures. Also known as the Brazilian Defense, it aims to unbalance the game through unexpected positions.",
    "Irish Gambit": "An offensive approach where White sacrifices the e5 pawn with 3.Nxe5 after 2...Nc6, gaining rapid development and piece activity. The sacrifice is sound but requires accurate play to maintain the advantage.",
    "Italian Game": "A classical and direct opening where White develops the kingside bishop to c4, exerting pressure on f7 and the kingside. Black has numerous flexible responses, making it a popular choice at all levels.",
    "King's Gambit": "One of the oldest and most romantic openings, where White sacrifices the f-pawn to open diagonals and attack Black's kingside. Though considered dubious at top levels, it retains practical importance below elite levels.",
    "King's Gambit Accepted": "Black accepts White's pawn sacrifice in the King's Gambit, leading to sharp, tactical positions where White has strong attacking chances but Black has material and defensive resources.",
    "King's Gambit Declined": "Black declines the gambit sacrifice, typically with moves like 2...Bc5 or a countergambit with 2...d5. This leads to more positional battles compared to the accepted lines.",
    "King's Knight Opening": "A flexible and solid approach where White plays 1.e4 e5 2.Nf3 without committing to the main lines like Ruy Lopez or Italian Game. It maintains options while following sound opening principles.",
    "King's Pawn Opening": "The broadest category of 1.e4 openings, covering positions after 1.e4 e5 where White has not yet committed to a specific system. It provides flexibility and allows for various continuations.",
    "Latvian Gambit": "An aggressive and dubious gambit by Black featuring 1.e4 e5 2...f5, offering a pawn for rapid counterplay. Though objectively poor, it leads to sharp, unbalanced positions with practical winning chances.",
    "Latvian Gambit Accepted": "White accepts the gambit pawn in the Latvian Gambit, leading to complex and tactical positions where Black's compensation through piece activity and open lines is questionable but offers practical complexity.",
    "Petrov's Defense": "A solid and symmetrical counterattacking defense where Black mirrors White's setup with 2...Nf6, avoiding the Ruy Lopez and Italian Game. It has a drawish reputation but contains sharp variations.",
    "Philidor Defense": "A solid but passive defense where Black plays 2...d6 early, creating a pawn shield and avoiding weaknesses. While cramped initially, it provides a very secure foundation for counterplay.",
    "Ponziani Opening": "A side opening featuring 1.e4 e5 2.Nf3 Nc6 3.c3, where White prepares to support the d4-advance with the c-pawn. It is solid but less popular than main-line openings, offering rich strategic play.",
    "Portuguese Opening": "A rare and experimental first move of 1.a3, where White prepares queenside expansion with b4 and develops slowly. It gives White unusual strategic ideas but allows Black significant flexibility.",
    "Ruy Lopez": "The most popular and theoretically important of all Open Games, where White's bishop on b5 exerts immediate pressure on Black's position. Extensively analyzed with countless variations, it remains the choice of world champions at all levels.",
    "Scotch Game": "A classical and aggressive opening where White plays 1.e4 e5 2.Nf3 Nc6 3.d4, challenging Black's center immediately. It leads to open, tactical positions with clear piece play and good winning chances for White.",
    "Three Knights Opening": "An unusual move order where White develops the c3-knight early with 1.e4 e5 2.Nf3 Nc6 3.Nc3, avoiding the Ruy Lopez. It offers a flexible setup but allows Black to transpose to many well-known systems.",
    "Vienna Gambit, with Max Lange Defense": "A sharp system arising from the Vienna Game where White plays f4 and Black responds with the Max Lange Defense, leading to tactical complications and open positions with mutual attacking chances.",
    "Vienna Game": "A flexible opening where White develops the c3-knight first, allowing f4 to follow later or adopting quieter setups like 3.Bc4 or 3.g3. It offers many transposition chances and strategic flexibility.",
}

FAMILY_REPUTATION = {
    "Bishop's Opening": "A respectable but less popular option compared to the Italian Game and Ruy Lopez. Plays well at all levels but offers fewer winning attempts than more theoretical mainlines.",
    "Bongcloud Attack": "Considered a joke opening by analysis and serious players; despite some unlikely successes in blitz, it is objectively bad and not recommended for serious play.",
    "Center Game": "A playable but slightly passive system for White; less popular than 3.Bb5 or 3.Bc4, it allows Black reasonable equality with accurate defense.",
    "Center Game Accepted": "Generally seen as slightly better for Black compared to other White second-move options. White has practical chances but needs to prove compensation.",
    "Danish Gambit": "A solid gambit with a long history of master games, but its popularity declined after Black discovered reliable defenses. Still viable at club level and in rapid games.",
    "Danish Gambit Accepted": "Offers White practical complications and attacking chances, particularly attractive for players who enjoy sharp positions and piece activity over material advantage.",
    "Danish Gambit Declined": "A solid defensive approach for Black; while avoiding complications, it gives Black a passive game, and the pawn on d4 can become a target.",
    "Dresden Opening": "An interesting but rarely played sideline; offers White some strategic ideas but generally considered less direct than main-line continuations.",
    "Elephant Gambit": "A dubious and rarely played gambit with low reputation; primarily useful as a surprise weapon against unprepared opponents in casual games.",
    "Four Knights Game": "A solid, drawish opening popular at club level; offers mutual chances but lacks the sharpness and theoretical testing of the Ruy Lopez and Italian Game.",
    "French Defense": "A highly respected and solid defense at all levels; while Black gets a cramped position, the solid structure and available counterplay make it a world championship weapon.",
    "Gunderam Defense": "A rare and unconventional system; little analyzed and unsuitable for serious competitive play, though it offers unpredictable positions for casual games.",
    "Irish Gambit": "A sound gambit with reasonable compensation; suitable for practical play but less popular than main-line gambits. Offers interesting practical chances.",
    "Italian Game": "A classical and popular opening at all levels; slightly more aggressive than the Ruy Lopez, it leads to rich middlegame play with chances for both sides.",
    "King's Gambit": "Historically one of the most popular openings; fell out of favor after 20th-century analytical improvements but retains popularity at lower levels and remains playable.",
    "King's Gambit Accepted": "A critical and theoretically important main line; offers White strong practical chances and attacking prospects with the extra space and open lines.",
    "King's Gambit Declined": "A solid choice for Black, avoiding the sharp complications of the accepted line while maintaining a playable game against White's space advantage.",
    "King's Knight Opening": "A solid and safe move; popular for maintaining flexibility without overcommitting. Offers few winning attempts but keeps the position under White's control.",
    "King's Pawn Opening": "Covers a wide range of openings with varying reputation; generally, 1.e4 is considered slightly advantageous for White but leads to balanced positions.",
    "Latvian Gambit": "Considered dubious and even the worst opening in chess by some authors; despite rare successes, it is not recommended for serious play without significant preparation.",
    "Latvian Gambit Accepted": "Though tactically complex, the gambit is objectively difficult for Black to justify; White's extra pawn and material advantage generally outweigh Black's compensation.",
    "Petrov's Defense": "A well-respected and solid defense used by world champions; while drawish, it provides reliable equality and has proven itself in top-level competition.",
    "Philidor Defense": "A solid but passive system; while very safe, it often leads to cramped and difficult-to-play positions for Black without clear counterplay in many lines.",
    "Ponziani Opening": "A solid but rarely played opening; it offers less than the main lines and allows Black good practical chances with flexible defensive setups.",
    "Portuguese Opening": "An experimental and rare move; considered eccentric and not suitable for serious competitive play, though it offers unusual strategic ideas.",
    "Ruy Lopez": "The most respected and widely played opening at the highest levels; used by world champions, it offers White excellent practical chances with rich, complex positions.",
    "Scotch Game": "A classical and sound opening with recent resurgence in popularity; offers White more direct play than other main lines with clear winning opportunities.",
    "Three Knights Opening": "A solid but flexible move order; less forcing than the Ruy Lopez and Italian Game, it allows Black good defensive resources through transpositions.",
    "Vienna Gambit, with Max Lange Defense": "A sharp and tactical system with good practical chances for White; requires precise play but offers interesting imbalances and attacking opportunities.",
    "Vienna Game": "A flexible opening with transposition richness; less theoretically demanding than main lines, it remains a respectable choice at all levels despite moderate popularity.",
}

NOTABLE_SUBVARIATIONS = {
}
